name: pyfin
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.4
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.6
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  firebase_messaging: ^6.0.16
  firebase_storage: null
  flushbar: ^1.10.4
  flutter_markdown: ^0.3.4
  flutter_mobx: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_svg: ^0.18.0
  fluttertoast: ^7.1.6
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: null
  image_picker: null
  international_phone_input: ^1.0.4
  localstorage: ^3.0.6+9
  mobx: ^1.1.1
  multiselect_formfield: ^0.1.5
  numeric_keyboard: ^1.0.0
  path_provider: ^1.6.27
  percent_indicator: ^2.1.9+1
  random_string: ^2.1.0
  shared_preferences: ^0.4.0
  slimy_card: ^1.0.4
  url_launcher: null
  velocity_x: ^1.0.1
  multi_select_flutter: ^3.1.8
  animated_splash_screen: ^1.0.1+2
  lottie: ^0.7.0+1
  change_app_package_name: ^0.1.2
  datetime_picker_formfield: ^1.0.0
  country_list_pick: ^1.0.1+3

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.2

  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/cover/
    - assets/gifs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
